name: 'Scan for LLM Code'
description: 'Check for LLM Usage'
branding: 
  icon: archive
  color: purple
inputs:
  text:
    description: 'LLM package to search for'
    required: true
outputs:
  http_response:
    description: 'The result from the Pangea API'
runs:
  using: 'node16'
  main: 'dist/index.js'
