name: "scan-on-pull"
on:
  pull_request_target:
    types: [opened]
jobs:
  testforLLM:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        AI: ["openai","langchain", "@cloudflare/workers-ai", "@aws-sdk/client-bedrock", "@huggingface/transformers", "cohere-ai", "anthropic", "stability-ai", "@pinecone-database/pinecone", "@vercel/ai", "grok-js", "@google/gemini"]
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        text: ${{matrix.AI}}