name: "test-on-issue"
on:
  issues:
    types: [opened, closed, reopened]
jobs:
  testforLLM:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mweinberger/pangea-github-action-scan@newtagforpangeatouseeventually
      with:
        text: "'openai','langchain', '@cloudflare/workers-ai', '@aws-sdk/client-bedrock', '@huggingface/transformers', 'cohere-ai', 'anthropic', 'stability-ai', '@pinecone-database/pinecone', '@vercel/ai', 'grok-js', '@google/gemini'"
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif