name: "units-test"
on:
  issues:
    types: [opened, closed, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: local
      uses: ./
      with:
        text: "test"
        token: ${{secrets.PANGEA_TOKEN}}
        domain: ${{secrets.PANGEA_DOMAIN}}