name: "test-on-issue"
on:
  issues:
    types: [opened, closed, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        text: "openai"
    - uses: actions/checkout@v4
    - uses: ./
      with:
        text: "langchain"
    - uses: actions/checkout@v4
    - uses: ./
      with:
        text: "@cloudflare/workers-ai"
    - uses: actions/checkout@v4
    - uses: ./
      with:
        text: "@aws-sdk/client-bedrock"
    - uses: actions/checkout@v4
    - uses: ./
      with:
        text: "@huggingface/transformers"
    - uses: actions/checkout@v4
    - uses: ./
      with:
        text: "cohere-ai"
    - uses: actions/checkout@v4
    - uses: ./
      with:
        text: "anthropic"
    - uses: actions/checkout@v4
    - uses: ./
      with:
        text: "stability-ai"
    - uses: actions/checkout@v4
    - uses: ./
      with:
        text: "@pinecone-database/pinecone"
    - uses: actions/checkout@v4
    - uses: ./
      with:
        text: "@vercel/ai"
    - uses: actions/checkout@v4
    - uses: ./
      with:
        text: "grok-js"
    - uses: actions/checkout@v4
    - uses: ./
      with:
        text: "@google/gemini"
